# Generated by Django 5.0.7 on 2024-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
